### ISSUE TITLE
notice 생성시 response 403 응답

### ISSUE THREAD

**Issue by MaccBass** [dailyrunner/TravelSync_client_new#15]
curl -X 'POST' \
  'http://34.83.150.5/notice' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "groupId": 10,
  "noticeDate": "2023-12-04 06:50",
  "noticeTitle": "dd",
  "noticeLatitude": 10.2,
  "noticeLongitude": -5.2
}'

위 형식대로 보낼 시 403 응답
body 내 각 변수별로 정확한 형식이 무엇인지 파악 필요

**Comment by Jhsysng** [comment]
'Authorization'이 없네요

**Comment by MaccBass** [comment]
> 'Authorization'이 없네요

해결
